name: tryflutter
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ar_flutter_plugin: ^0.7.3
  camera: ^0.10.4
  path_provider: ^2.0.14
  flutter_icons: ^1.1.0
  arcore_flutter_plugin: ^0.1.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
